import { Evidence } from "@/domain/evidence";
import { AgentResult } from "@/domain/agent";

export interface EvidenceSummary {
  all: Evidence[];
  byClassification: Record<string, number>;
  averageConfidence: number;
}

// Collects evidence across all agent results for one candidate, de-duplicating by id.
// Never upgrades a classification — everything in Phase 1 stays MOCK, since that's the
// honest label for data generated by the seeded demo catalog.
export function collectEvidence(agentResults: AgentResult[]): EvidenceSummary {
  const seen = new Map<string, Evidence>();
  for (const result of agentResults) {
    for (const e of result.evidence) {
      seen.set(e.id, e);
    }
  }
  const all = [...seen.values()];

  const byClassification: Record<string, number> = {};
  for (const e of all) {
    byClassification[e.classification] = (byClassification[e.classification] ?? 0) + 1;
  }

  const averageConfidence =
    all.length > 0 ? all.reduce((s, e) => s + e.confidence, 0) / all.length : 0;

  return { all, byClassification, averageConfidence: Math.round(averageConfidence) };
}
